"""
export_c.py — write the model and every feature constant into C source files
for the ESP32 firmware. Nothing here is re-derived in C; it is all COPIED from
the exact Python objects that training used (CLAUDE.md §6 risk 1).

Run (from training, after quantize.py):
    ../.venv/Scripts/python.exe export_c.py

Writes (into firmware/main/):
  model_data.h / model_data.cc   model_int8.tflite as a byte array
  feature_tables.h               Hann window, mel filterbank (sparse), per-band
                                 norm mean/std, int8 input/output quantization,
                                 threshold, class order

Re-run this after EVERY retrain or re-quantization. The header records the
sha256 of the model it was generated from, and the firmware prints it at boot,
so a board running a stale model is visible in the serial log.
"""

import hashlib
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config as C  # noqa: E402
import features as F  # noqa: E402

OUT_DIR = os.path.join(C.PROTO, "firmware", "main")


def cfloat(v):
    """A float literal C accepts: 1 -> 1.0f, 1e-10 -> 1e-10f."""
    s = f"{float(v):.9g}"
    if not any(c in s for c in ".en"):
        s += ".0"
    return s + "f"


def fmt_floats(a, per_line=6):
    vals = [cfloat(v) for v in np.asarray(a).ravel()]
    lines = [", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line)]
    return "    " + ",\n    ".join(lines)


def fmt_bytes(b, per_line=16):
    lines = [", ".join(f"0x{x:02x}" for x in b[i:i + per_line]) for i in range(0, len(b), per_line)]
    return "    " + ",\n    ".join(lines)


def main():
    tfl_path = os.path.join(C.MODEL_DIR, "model_int8.tflite")
    with open(tfl_path, "rb") as f:
        blob = f.read()
    with open(os.path.join(C.MODEL_DIR, "quant_report.json")) as f:
        q = json.load(f)
    norm = F.Normalizer.load(os.path.join(C.MODEL_DIR, "norm.json"))
    sha = hashlib.sha256(blob).hexdigest()
    os.makedirs(OUT_DIR, exist_ok=True)

    # --- model -------------------------------------------------------------
    with open(os.path.join(OUT_DIR, "model_data.h"), "w", newline="\n") as f:
        f.write(f"""// GENERATED by training/export_c.py. Do not edit.
#pragma once
#ifdef __cplusplus
extern "C" {{
#endif
extern const unsigned char g_model[];
extern const unsigned int g_model_len;
#define MODEL_SHA256 "{sha}"
#ifdef __cplusplus
}}
#endif
""")
    with open(os.path.join(OUT_DIR, "model_data.cc"), "w", newline="\n") as f:
        f.write(f"""// GENERATED by training/export_c.py from model/model_int8.tflite.
// sha256 {sha}
#include "model_data.h"

// alignas(8): TFLite Micro reads the flatbuffer in place and needs it aligned.
alignas(8) const unsigned char g_model[] = {{
{fmt_bytes(blob)}
}};
const unsigned int g_model_len = {len(blob)};
""")

    # --- feature tables ----------------------------------------------------
    # The mel matrix is 40 x 201 but mostly zeros: each band covers a
    # contiguous run of FFT bins. Store (first bin, count) per band plus the
    # packed non-zero weights — ~1.3 KB instead of 32 KB, and C loops over
    # far fewer bins.
    starts, counts, weights = [], [], []
    for band in F.MEL_FB:
        nz = np.nonzero(band)[0]
        lo, hi = int(nz[0]), int(nz[-1])
        starts.append(lo)
        counts.append(hi - lo + 1)
        weights.extend(band[lo:hi + 1])        # includes any interior zeros: exact

    thr = float(q["threshold"])
    kw = C.CLASSES.index("keyword")
    with open(os.path.join(OUT_DIR, "feature_tables.h"), "w", newline="\n") as f:
        f.write(f"""// GENERATED by training/export_c.py. Do not edit.
// PARITY CONTRACT: mirrors training/features.py exactly.
// Model sha256: {sha}
#pragma once
#include <stdint.h>

#define FE_SAMPLE_RATE   {F.SR}
#define FE_CLIP_SAMPLES  {F.CLIP}
#define FE_WIN           {F.WIN}
#define FE_HOP           {F.HOP}
#define FE_N_FFT         {F.N_FFT}
#define FE_N_BINS        {F.N_FFT // 2 + 1}
#define FE_N_MELS        {F.N_MELS}
#define FE_N_FRAMES      {F.N_FRAMES}
#define FE_LOG_FLOOR     {cfloat(F.LOG_FLOOR)}
#define FE_MEL_WEIGHTS   {len(weights)}

// Model input quantization: q = clamp(round(F / scale) + zp, -128, 127)
#define KWS_INPUT_SCALE       {cfloat(q['input']['scale'])}
#define KWS_INPUT_ZERO_POINT  {q['input']['zero_point']}
// Model output: p = scale * (q - zp)
#define KWS_OUTPUT_SCALE      {cfloat(q['output']['scale'])}
#define KWS_OUTPUT_ZERO_POINT {q['output']['zero_point']}
#define KWS_N_CLASSES         {len(C.CLASSES)}
#define KWS_KEYWORD_INDEX     {kw}
#define KWS_THRESHOLD         {cfloat(thr)}   // chosen on validation by train.py
static const char *const KWS_CLASS_NAMES[KWS_N_CLASSES] = {{ {", ".join(f'"{c}"' for c in C.CLASSES)} }};

// Periodic Hann window, {F.WIN} samples.
static const float FE_WINDOW[FE_WIN] = {{
{fmt_floats(F.WINDOW)}
}};

// Mel filterbank, HTK, no norm, {F.FMIN:g}-{F.FMAX:g} Hz, stored sparse:
// band b uses FFT bins FE_MEL_START[b] .. FE_MEL_START[b] + FE_MEL_COUNT[b] - 1,
// with weights read consecutively from FE_MEL_W.
static const uint16_t FE_MEL_START[FE_N_MELS] = {{ {", ".join(map(str, starts))} }};
static const uint16_t FE_MEL_COUNT[FE_N_MELS] = {{ {", ".join(map(str, counts))} }};
static const float FE_MEL_W[FE_MEL_WEIGHTS] = {{
{fmt_floats(weights)}
}};

// Per-band normalisation (model/norm.json): F = (L - mean) / std
static const float FE_NORM_MEAN[FE_N_MELS] = {{
{fmt_floats(norm.mean)}
}};
static const float FE_NORM_STD[FE_N_MELS] = {{
{fmt_floats(norm.std)}
}};
""")
    print(f"model {len(blob):,} bytes, sha256 {sha[:16]}...")
    print(f"mel weights {len(weights)} (dense would be {F.MEL_FB.size})")
    print(f"wrote model_data.h, model_data.cc, feature_tables.h -> {OUT_DIR}")


if __name__ == "__main__":
    main()
