// GENERATED by training/export_c.py. Do not edit.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char g_model[];
extern const unsigned int g_model_len;
#define MODEL_SHA256 "75997aadce3e9f7c9ae0e9b9f2ad1d38d959ed391b06aad0fb31a9387346a22f"
#ifdef __cplusplus
}
#endif
