// GENERATED by training/export_c.py. Do not edit.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char g_model[];
extern const unsigned int g_model_len;
#define MODEL_SHA256 "e9e10d52a17832fb1c942e557371ef6a6947d5fe881890a0350676095b640735"
#ifdef __cplusplus
}
#endif
